version: '3.8'

services:
  frontend-local:
    image: ghcr.io/nervus-tech/nervus-frontend:v1.1.0-local
    container_name: frontend-local
    ports:
      - "8122:3000"
    environment:
      - NODE_ENV=production
      - EUREKA_URL=http://eureka-local:8761
      - SERVICE_PORT=3000
      - SERVICE_NAME=FRONTEND
      - HOST_NAME=frontend-local
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    networks:
      - nervus-local-network

networks:
  nervus-local-network:
    external: true 