version: '3.8'

services:
  frontend:
    image: ghcr.io/nervus-tech/nervus-frontend:v1.1.0-staging
    container_name: frontend-staging
    ports:
      - "8120:3000"
    environment:
      - NODE_ENV=production
      - EUREKA_URL=http://eureka:8761
      - SERVICE_PORT=3000
      - SERVICE_NAME=FRONTEND
      - HOST_NAME=frontend-staging
    networks:
      - nervus-infrastructure_default

networks:
  nervus-infrastructure_default:
    external: true 